### ISSUE TITLE
Warning in loader.py in Django 1.8

### ISSUE THREAD

**Issue by mapeveri** [frankban/django-endless-pagination#85]
In Django 1.8 when execute the server display the following warning:

RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9. from django.utils.importlib import import_module

**Comment by mapeveri** [comment]
I sent the pull request.

**Comment by BlastPy** [comment]
The same problem. How to fix ?

**Comment by mapeveri** [comment]
Hi @BlastPy, the problem is solved as well:

In the file loader.py add this:
try:
    from importlib import import_module
except ImportError:
    from django.utils.importlib import import_module

**Comment by WangWenchao** [comment]
the repo is not maintained? 

the latest version is released  in 2013 .


I add  the suggest in loader.py , the problem is still exists

**Comment by Fingel** [comment]
A bit worrisome, this repo appears abandoned?

**Comment by gungorbudak** [comment]
I don't know if I'm allowed to but I forked and fixed it here: https://github.com/gungorbudak/django-endless-pagination. Also, used Bootstrap 3 theme for the templates, FYI by taking some help from https://github.com/mozillazg/django-endless-pagination-bootstrap-theme

To upgrade, you do the following:
>$ cd ~/Downloads
>$ git clone https://github.com/gungorbudak/django-endless-pagination.git
>$ cd django-endless-pagination
>$ sudo pip uninstall django-endless-pagination
>$ sudo python setup.py install

And, the warning is gone.

**Comment by shtalinberg** [comment]
try my app
https://github.com/shtalinberg/django-el-pagination
my repo will be maintained
